### PR TITLE
Work around chrome bug

### PR DESCRIPTION
**Pull request by thomassuckow**
Chrome rounds down the scrollTop, make it large enough to not result in 0

https://bugs.chromium.org/p/chromium/issues/detail?id=584443

### CODE REVIEW

**Comment by cosmicexplorer** [comment]
Sorry, I haven't looked at this or used this in a while and I wrote it when I wasn't that great at js. Can you give an example (some html, perhaps) of what this fixes?

**Comment by thomassuckow** [comment]
http://jsfiddle.net/thomassuckow/gued0nzn/6/

Resizing the preview pane causes the box to change colors

In broken browsers (Chrome 47, Chrome 48, Safari unknown version), it doesn't work when growing vertically because of a rounding bug.

**Comment by cosmicexplorer** [comment]
Oh oops, didn't see that you already posted that in the bug report. Thanks for responding so fast.

However, I'd recommend making a pull request on the [repo I pulled the code from](https://github.com/sdecima/javascript-detect-element-resize). This was just a copy/paste of the repo's code into an NPM package, since at that time that repo didn't have an NPM package of its own. I'll probably delete this in a few days.

**Comment by thomassuckow** [comment]
https://github.com/sdecima/javascript-detect-element-resize/issues/36

Also, yours isn't the same. You export a module, the "official" one modifies the window object.

**Comment by cosmicexplorer** [comment]
Ok, also didn't see that issue for some reason. This looks good.

**Pull request merged**
